# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (every other hour)
  schedule: [{cron: "0 */2 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: yobson1
          template: classic
          base: header, activity, repositories, metadata
          config_display: large
          config_octicon: yes
          config_timezone: Europe/London
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: percentage
          plugin_languages_ignored: lua
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_stock: yes
          plugin_stock_duration: 1mo
          plugin_stock_interval: 5m
          plugin_stock_symbol: GME
          plugin_stock_token: ${{ secrets.YAHOO_TOKEN }}
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_TOKEN }}
          plugin_music_mode: top
          plugin_music_top_type: artists
          plugin_music_time_range: medium
          repositories_forks: yes
          extras_css: |
            h1, h2 {
              color: #ff76cd;
            }
          config_order: base.header, base.activity+community, base.repositories, achievements, music, stock, languages
